export const idlFactory = ({ IDL }) => {
  const NftError = IDL.Variant({
    'UnauthorizedOperator' : IDL.Null,
    'SelfTransfer' : IDL.Null,
    'TokenNotFound' : IDL.Null,
    'UnauthorizedOwner' : IDL.Null,
    'NotFound' : IDL.Null,
    'SelfApprove' : IDL.Null,
    'OperatorNotFound' : IDL.Null,
    'ExistedNFT' : IDL.Null,
    'OwnerNotFound' : IDL.Null,
    'Other' : IDL.Text,
  });
  const Result = IDL.Variant({ 'ok' : IDL.Nat, 'err' : NftError });
  const Metadata = IDL.Record({
    'logo' : IDL.Opt(IDL.Text),
    'name' : IDL.Opt(IDL.Text),
    'created_at' : IDL.Nat64,
    'upgraded_at' : IDL.Nat64,
    'custodians' : IDL.Vec(IDL.Principal),
    'symbol' : IDL.Opt(IDL.Text),
  });
  const NMCProperties = IDL.Record({
    'xp' : IDL.Nat64,
    'bankooText' : IDL.Vec(IDL.Text),
    'mental' : IDL.Nat64,
    'ringType' : IDL.Text,
    'powerUps' : IDL.Vec(IDL.Nat64),
    'styles' : IDL.Vec(IDL.Text),
    'alias' : IDL.Text,
    'notiOn' : IDL.Bool,
    'networkClass' : IDL.Text,
    'fsOn' : IDL.Bool,
    'imageCompData' : IDL.Vec(IDL.Nat8),
    'rank' : IDL.Nat64,
    'network' : IDL.Vec(IDL.Text),
    'ancestorsNames' : IDL.Vec(IDL.Text),
    'email' : IDL.Text,
    'sight' : IDL.Nat64,
    'speed' : IDL.Nat64,
    'discoveredProgress' : IDL.Float64,
    'story' : IDL.Record({
      'title' : IDL.Text,
      'imagesUri' : IDL.Vec(IDL.Text),
      'text' : IDL.Text,
      'videoURI' : IDL.Text,
    }),
    'progress' : IDL.Nat64,
    'musicLevel' : IDL.Float64,
    'domains' : IDL.Vec(IDL.Nat64),
    'landRank' : IDL.Nat64,
    'category' : IDL.Text,
    'landNumber' : IDL.Nat64,
    'endurance' : IDL.Float64,
    'power' : IDL.Nat64,
    'physical' : IDL.Nat64,
    'identifier' : IDL.Text,
    'ancestorsImages' : IDL.Vec(IDL.Nat8),
    'soundLevel' : IDL.Float64,
    'earthText' : IDL.Vec(IDL.Text),
    'linked' : IDL.Bool,
    'playerLocation' : IDL.Nat64,
    'health' : IDL.Nat64,
    'discovered' : IDL.Vec(IDL.Text),
  });
  const Result_3 = IDL.Variant({
    'ok' : IDL.Opt(IDL.Principal),
    'err' : NftError,
  });
  const TokenMetadata = IDL.Record({
    'transferred_at' : IDL.Opt(IDL.Nat64),
    'transferred_by' : IDL.Opt(IDL.Principal),
    'owner' : IDL.Opt(IDL.Principal),
    'operator' : IDL.Opt(IDL.Principal),
    'approved_at' : IDL.Opt(IDL.Nat64),
    'approved_by' : IDL.Opt(IDL.Principal),
    'properties' : IDL.Vec(NMCProperties),
    'is_burned' : IDL.Bool,
    'token_identifier' : IDL.Nat,
    'burned_at' : IDL.Opt(IDL.Nat64),
    'burned_by' : IDL.Opt(IDL.Principal),
    'minted_at' : IDL.Nat64,
    'minted_by' : IDL.Principal,
  });
  const Result_2 = IDL.Variant({
    'ok' : IDL.Vec(TokenMetadata),
    'err' : NftError,
  });
  const SupportedInterface = IDL.Record({
    'Burn' : IDL.Null,
    'Mint' : IDL.Null,
    'Approval' : IDL.Null,
    'TransactionHistory' : IDL.Null,
  });
  const Result_1 = IDL.Variant({ 'ok' : TokenMetadata, 'err' : NftError });
  return IDL.Service({
    'adminUser' : IDL.Func([], [IDL.Text], ['query']),
    'alphaLedger' : IDL.Func([], [IDL.Nat], ['query']),
    'balanceOf' : IDL.Func([IDL.Principal], [Result], ['query']),
    'custodians' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
    'logo' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
    'metadata' : IDL.Func([], [Metadata], ['query']),
    'mint' : IDL.Func(
        [IDL.Principal, IDL.Nat, IDL.Vec(NMCProperties)],
        [Result],
        [],
      ),
    'name' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
    'operatorOf' : IDL.Func([IDL.Nat], [Result_3], ['query']),
    'operatorTokenMetadata' : IDL.Func([IDL.Principal], [Result_2], ['query']),
    'ownerOf' : IDL.Func([IDL.Nat], [Result_3], ['query']),
    'ownerTokenMetadata' : IDL.Func([IDL.Principal], [Result_2], ['query']),
    'savetoTemp' : IDL.Func(
        [IDL.Principal, IDL.Nat, IDL.Vec(NMCProperties)],
        [Result],
        [],
      ),
    'setCustodians' : IDL.Func([IDL.Vec(IDL.Principal)], [], []),
    'setLogo' : IDL.Func([IDL.Text], [], []),
    'setName' : IDL.Func([IDL.Text], [], []),
    'setSymbol' : IDL.Func([IDL.Text], [], []),
    'supportedInterfaces' : IDL.Func(
        [],
        [IDL.Vec(SupportedInterface)],
        ['query'],
      ),
    'symbol' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
    'tempMetaData' : IDL.Func([IDL.Nat], [Result_1], ['query']),
    'tokenMetadata' : IDL.Func([IDL.Nat], [Result_1], ['query']),
    'totalSupply' : IDL.Func([], [IDL.Nat], ['query']),
    'updateTemp' : IDL.Func(
        [IDL.Principal, IDL.Nat, IDL.Vec(NMCProperties)],
        [Result],
        [],
      ),
  });
};
export const init = ({ IDL }) => { return []; };
